version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - moneyigos
  assignees:
    - moneyigos
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
# Fetch and update latest `github-actions` pkgs
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - moneyigos
  assignees:
    - moneyigos
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          echo installing codecov
          yarn add codecov
          echo installing dependencies
          yarn
          echo building application
          yarn build
          echo linting application
          yarn lint
